// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditController from "./edit_controller"
application.register("edit", EditController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ReservationController from "./reservation_controller"
application.register("reservation", ReservationController)

import SearchBarController from "./search_bar_controller"
application.register("search-bar", SearchBarController)
